# Adds book on opening issue
name: addBook

on:
  issues:
    types: [opened]

jobs:
  addBook:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest     
    if: startsWith(github.event.issue.title, 'addBook|')
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access
      - uses: actions/checkout@v2

      # Set up Node environment
      - name: Set up Node 14
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'
      
      - name: Install dependencies
        run: npm install
        
      - name: Add Book 
        env:
          ISSUE_TITLE: ${{ github.event.issue.body }}
        run: |
          echo "${{ github.event.issue.body }}"
          echo "${{ github.event.issue.title }}"
          
